[build]
  base    = "client"
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/api/*"
  to     = "https://visa-analytics-api.onrender.com/api/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
