services:
  - type: web
    name: visa-analytics-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: visaAnalytics
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4001
